// constants/NOTIFICATION_TYPE.js

const NOTIFICATION_TYPE = {
    FOLLOW: 'FOLLOW',
    RETWEET: 'RETWEET',
    COMMENT: 'COMMENT',
    LIKE: 'LIKE',
    RECOMMENT: 'RECOMMENT',
    RANDOMBOX: 'RANDOMBOX',
    GROUPAPPLY: 'GROUPAPPLY',
    GROUPAPPLY_APPROVE: 'GROUPAPPLY_APPROVE',
    GROUPAPPLY_REJECT: 'GROUPAPPLY_REJECT',
    ADMIN_NOTI: 'ADMIN_NOTI',
    ANIMAL_FRIENDS: 'ANIMAL_FRIENDS',
};

module.exports = NOTIFICATION_TYPE;
